### ISSUE TITLE
Time is a maskedconstant in the merged netcdf file ? 

### ISSUE THREAD

**Issue by jeremyfix** [copernicusmarine/cmemsapi#3] opened 2022-11-24 07:56 UTC
* Copernicus Marine API version: 0.1.17
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description

I am downloading data with `cmems get`. Although all the individual nc files have `numpy.float64` for all the values of the `time` variable, in the merged CDF file, only the first 365 values are `numpy.float64`, the others are `numpy.ma.core.MaskedConstant`.

I am note sure about what is a `numpy.ma.core.MaskedConstant` but I believe this is incorrect. For example :

- if I try to plot the `time` variable with Panoply, on the merged CDF file, it complains that `Axis includes NaN value(s)`
- if I try to plot the `time` variable with Panoply of every individual CDF file, the ones that were fused, it works

### What I Did

To get the data :

**download_data.sh**
```
longitude_min=6
longitude_max=9
latitude_min=41.5
latitude_max=44.5
depth_min=0
depth_max=500
date_min="2010-01-01 00:00:00"
date_max="2012-07-01 00:00:00"

# mld mlotst 
key=mld
variable=mlotst
cmust get --user=$CMEMS_USERNAME --pwd=$CMEMS_PASSWORD --view_myscript="python -m motuclient --motu https://my.cmems-du.eu/motu-web/Motu --service-id MEDSEA_MULTIYEAR_PHY_006_004-TDS --product-id med-cmcc-$key-rean-d --longitude-min $longitude_min --longitude-max $longitude_max --latitude-min $latitude_min --latitude-max $latitude_max --date-min \"$date_min\" --date-max \"$date_max\" --depth-min $depth_min --depth-max $depth_max --variable $variable --out-dir <OUTPUT_DIRECTORY> --out-name <OUTPUT_FILENAME> --user <USERNAME> --pwd <PASSWORD>" --delete_files=False
```

This will create files in `copernicus-tmp-data` and `copernicus-processed-data`.  If you try to plot `time` with Panoply with `copernicus-processed-data/CMEMS-MEDSEA_006_004-mlotst-2010_2012.nc` it fails, but works if you plot `copernicus-tmp-data/CMEMS-MEDSEA_006_004-mlotst-2010.nc`, `copernicus-tmp-data/CMEMS-MEDSEA_006_004-mlotst-2011.nc` or `copernicus-tmp-data/CMEMS-MEDSEA_006_004-mlotst-2012.nc`

### Python versions

I dump below the version of the python libs;  As the `to_nc4` function is calling xarray, its version can be of interest. I add the versions of the others if necessary.

```
(venv) ➜  Exploration git:(main) ✗ pip freeze
asttokens==2.1.0
backcall==0.2.0
certifi==2022.9.24
cftime==1.6.2
charset-normalizer==2.1.1
click==8.1.3
cloudpickle==2.2.0
cmemsapi==0.1.17
dask==2022.11.1
decorator==5.1.1
executing==1.2.0
fire==0.4.0
fsspec==2022.11.0
funcy==1.17
idna==3.4
ipython==8.6.0
jedi==0.17.2
locket==1.0.0
lxml==4.9.1
matplotlib-inline==0.1.6
motuclient==1.8.4
netCDF4==1.5.4
numpy==1.23.5
packaging==21.3
pandas==1.5.1
parso==0.7.1
partd==1.3.0
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.33
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
PyYAML==6.0
requests==2.28.1
scipy==1.9.3
six==1.16.0
stack-data==0.6.1
termcolor==2.1.1
toolz==0.12.0
traitlets==5.5.0
urllib3==1.26.12
wcwidth==0.2.5
xarray==2022.11.0
```

**Comment by copernicusmarine** [comment] 2022-11-28 08:33
Hi @jeremyfix , many thanks for such a detailed report! We've checked internally and found out that the toolbox is not related to this behavior. 
It works as expected for many datasets, you can give a try to this query:

```
longitude_min=6
longitude_max=9
latitude_min=41.5
latitude_max=44.5
depth_min=0
depth_max=500
date_min="2020-10-01 00:00:00"
date_max="2022-07-01 23:59:59"

# mld mlotst 
key=mld
variable=mlotst
cmust get --user=$CMEMS_USERNAME --pwd=$CMEMS_PASSWORD --view_myscript="python -m motuclient --motu https://nrt.cmems-du.eu/motu-web/Motu --service-id GLOBAL_ANALYSIS_FORECAST_PHY_001_024-TDS --product-id global-analysis-forecast-phy-001-024 --longitude-min $longitude_min --longitude-max $longitude_max --latitude-min $latitude_min --latitude-max $latitude_max --date-min \"$date_min\" --date-max \"$date_max\" --depth-min $depth_min --depth-max $depth_max --variable $variable --out-dir <OUTPUT_DIRECTORY> --out-name <OUTPUT_FILENAME> --user <USERNAME> --pwd <PASSWORD>" --forcestack="year"
```

Our investigations lead to the **netcdf library** and the way datasets held by the product you linked **have been packed**, there is something in the attributes that does not allow to combine NetCDF files along the time dimension **to be properly decoded by Panoply**.

It can be easily reproduced performing a merged manually using this general code which shows that toolbox is not the root cause:
```
import xarray as xr
import glob
# Define the input data directory
input_data_dir = "/input/data/directory"
# Collect all netcdf file names in the data directory
filenames = glob.glob(f"{input_data_dir}/*.nc")
# Write in a single netcdf file
xr.open_mfdataset(filenames).to_netcdf("/output/data/directory/name.nc")
```

We have raised an internal request for change but because there is **no issue to manipulate the merged data in Python**:
![image](https://user-images.githubusercontent.com/51791874/204230277-0a9f260f-3ae5-4f8c-b541-051ce817b016.png)

As a consequence it's not a blocking situation (except for Panoply) and thus, this may take a while.

Thanks again for your report! We'll include Panoply in unitest for future!

Best regards,

**Comment by jeremyfix** [comment] 2022-11-28 15:43
Thank you for your investigations. Indeed, you are right that reading the files with xarray, the time variable is decoded correctly. 

I realize I did not mention all the details in my initial issue report. 

Although  reading the time variable fails with Panoply, it also fails if we read it with the netCDF4 python library. And that's the point I forgot to mention in my initial report. The maskedconstant is reported when the file is opened with netCDF4.

For example, if I merge the nc files with xarray as you did. Then, opening the files with xarray, we can list the times, plot the variables, etc...

However, if we :

```
import netCDF4

nc = netCDF4.Dataset(fp)
times = list(nc["time"][:])
for i, v in enumerate(times):
     print(i, type(v))
```

This is where I get some float for the first year and maskedconstant for the next;  

I'm not very fluent in xarray and netCDF4 and  I cannot state if this is expected or not ; I took the case of Panoply not being able to plot that variable as a second justification that the time variable was not encoded correctly . However, as xarray is decoding it correctly , it seems I'm wrong. 

As xarray is reading the file correctly, as you stated this "issue" is not related to your toolbox and you can certainly safely close it;  It might be more on the side of netCDF4 and panoply. 

Best;

**Comment by copernicusmarine** [comment] 2022-11-28 16:04
Many thanks @jeremyfix ! Closing issue.

**Closed as completed by copernicusmarine** 2022-11-28 16:04 UTC
